"""create feedback table

Revision ID: 609abfc5a291
Revises: 
Create Date: 2026-05-23 21:03:51.435588

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '609abfc5a291'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('feedback',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('text', sa.String(length=5000), nullable=False),
    sa.Column('source', sa.Enum('email', 'slack', 'app', 'other', name='feedbacksource'), nullable=False),
    sa.Column('customer_email', sa.String(), nullable=True),
    sa.Column('category', sa.String(length=50), server_default='uncategorized', nullable=False),
    sa.Column('priority', sa.String(length=50), server_default='medium', nullable=False),
    sa.Column('reviewed', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_feedback_category'), 'feedback', ['category'], unique=False)
    op.create_index(op.f('ix_feedback_created_at'), 'feedback', ['created_at'], unique=False)
    op.create_index(op.f('ix_feedback_reviewed'), 'feedback', ['reviewed'], unique=False)
    op.create_index(op.f('ix_feedback_source'), 'feedback', ['source'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_feedback_source'), table_name='feedback')
    op.drop_index(op.f('ix_feedback_reviewed'), table_name='feedback')
    op.drop_index(op.f('ix_feedback_created_at'), table_name='feedback')
    op.drop_index(op.f('ix_feedback_category'), table_name='feedback')
    op.drop_table('feedback')
    # ### end Alembic commands ###
