def test_x_request_id_is_echoed(client):
    """Test that X-Request-ID is echoed back, or generated if not provided."""
    # Case 1: Provided by the client
    response = client.get("/health", headers={"X-Request-ID": "custom-id-999"})
    assert response.headers.get("X-Request-ID") == "custom-id-999"
    
    # Case 2: Generated by the server
    response_generated = client.get("/health")
    assert "X-Request-ID" in response_generated.headers
